name: mightyweb
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BASE
  nb_utils: ^7.1.8
  google_fonts: ^6.3.2

  #UI
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.2
  package_info_plus: ^9.0.0
  flutter_speed_dial: ^7.0.0
  flutter_native_splash: ^2.4.6

  #STATE MANAGEMENT
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  #STORAGE & PERMISSION
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1

  #CONNECTIVITY
  http: ^1.5.0
  share_plus: ^12.0.0
  url_launcher: ^6.3.2
  store_redirect: ^2.0.4

  #Firebase
  firebase_in_app_messaging: ^0.9.0+2
  firebase_messaging: ^16.0.2
  firebase_core: ^4.1.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.3.4

  # ADS
  google_mobile_ads: ^6.0.0
  facebook_audience_network: ^1.0.1

  # WEB TOOLS
  flutter_inappwebview: ^6.1.5

  qr_code_scanner: ^1.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.9.0
  mobx_codegen: ^2.7.4
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  js: ^0.6.3
  http: ^1.2.1
  web: ^0.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 900
